// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAor1y5iNYkOmGByotaYH4fBdy5N-5JKHc',
    appId: '1:28372496889:web:154cad917d0c69198d4d28',
    messagingSenderId: '28372496889',
    projectId: 'flutter-quiz-95bee',
    authDomain: 'flutter-quiz-95bee.firebaseapp.com',
    storageBucket: 'flutter-quiz-95bee.appspot.com',
    measurementId: 'G-3SE37XC28P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv8czQWt3fzZE40euDYBi3PU__-Dgg6c0',
    appId: '1:28372496889:android:9431b4f72b245c278d4d28',
    messagingSenderId: '28372496889',
    projectId: 'flutter-quiz-95bee',
    storageBucket: 'flutter-quiz-95bee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRp5Sx8JO_URZW_PbfEB1zwyBGFk_19tg',
    appId: '1:28372496889:ios:4debd7a27c3494d48d4d28',
    messagingSenderId: '28372496889',
    projectId: 'flutter-quiz-95bee',
    storageBucket: 'flutter-quiz-95bee.appspot.com',
    androidClientId: '28372496889-qki57ug33v6fkil6h9hb3mdno2buchkg.apps.googleusercontent.com',
    iosClientId: '28372496889-1orcb10hve76v1po1n43c6ruvr66taqa.apps.googleusercontent.com',
    iosBundleId: 'io.shtibs.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRp5Sx8JO_URZW_PbfEB1zwyBGFk_19tg',
    appId: '1:28372496889:ios:ab9efc26f6e0e7978d4d28',
    messagingSenderId: '28372496889',
    projectId: 'flutter-quiz-95bee',
    storageBucket: 'flutter-quiz-95bee.appspot.com',
    androidClientId: '28372496889-qki57ug33v6fkil6h9hb3mdno2buchkg.apps.googleusercontent.com',
    iosClientId: '28372496889-n2sdjlms2tk23j158nu3jra86hq0pd2n.apps.googleusercontent.com',
    iosBundleId: 'io.shtibs.quiz.RunnerTests',
  );
}
